import type { Incident, Resource, Scenario, Sector } from './types'

const sectors: Sector[] = [
  {
    id: 'north-grid',
    name: 'North Grid Exchange',
    zone: 'Energy',
    population: 122000,
    criticality: 0.95,
    position: { x: 16, y: 18 },
    dependencies: ['central-hospital', 'river-harbor'],
    telemetry: { power: 72, medical: 86, mobility: 78, network: 84, water: 81, trust: 76 },
  },
  {
    id: 'central-hospital',
    name: 'Central Hospital Ring',
    zone: 'Health',
    population: 88000,
    criticality: 1,
    position: { x: 48, y: 23 },
    dependencies: ['north-grid', 'data-corridor'],
    telemetry: { power: 81, medical: 69, mobility: 68, network: 76, water: 86, trust: 82 },
  },
  {
    id: 'river-harbor',
    name: 'River Harbor Logistics',
    zone: 'Supply',
    population: 61000,
    criticality: 0.86,
    position: { x: 78, y: 30 },
    dependencies: ['east-artery', 'data-corridor'],
    telemetry: { power: 78, medical: 83, mobility: 62, network: 74, water: 69, trust: 71 },
  },
  {
    id: 'data-corridor',
    name: 'Data Corridor',
    zone: 'Network',
    population: 44000,
    criticality: 0.92,
    position: { x: 31, y: 48 },
    dependencies: ['north-grid'],
    telemetry: { power: 88, medical: 84, mobility: 83, network: 63, water: 84, trust: 80 },
  },
  {
    id: 'old-city',
    name: 'Old City Dense Block',
    zone: 'Residential',
    population: 214000,
    criticality: 0.81,
    position: { x: 55, y: 53 },
    dependencies: ['central-hospital', 'north-grid'],
    telemetry: { power: 75, medical: 71, mobility: 55, network: 72, water: 64, trust: 62 },
  },
  {
    id: 'east-artery',
    name: 'East Artery Interchange',
    zone: 'Mobility',
    population: 97000,
    criticality: 0.88,
    position: { x: 86, y: 57 },
    dependencies: ['river-harbor'],
    telemetry: { power: 83, medical: 80, mobility: 58, network: 78, water: 76, trust: 69 },
  },
  {
    id: 'university-quarter',
    name: 'University Quarter',
    zone: 'Education',
    population: 134000,
    criticality: 0.72,
    position: { x: 19, y: 75 },
    dependencies: ['data-corridor', 'central-hospital'],
    telemetry: { power: 82, medical: 78, mobility: 79, network: 81, water: 74, trust: 86 },
  },
  {
    id: 'south-reservoir',
    name: 'South Reservoir',
    zone: 'Water',
    population: 52000,
    criticality: 0.91,
    position: { x: 51, y: 84 },
    dependencies: ['north-grid'],
    telemetry: { power: 76, medical: 82, mobility: 74, network: 73, water: 59, trust: 73 },
  },
  {
    id: 'airport-node',
    name: 'Airport Relief Node',
    zone: 'Airbridge',
    population: 69000,
    criticality: 0.84,
    position: { x: 83, y: 83 },
    dependencies: ['east-artery', 'data-corridor'],
    telemetry: { power: 86, medical: 85, mobility: 73, network: 79, water: 77, trust: 81 },
  },
]

const resources: Resource[] = [
  {
    id: 'r-grid-alpha',
    name: 'Grid Swarm Alpha',
    kind: 'power',
    homeSectorId: 'north-grid',
    position: { x: 14, y: 16 },
    capabilities: ['restore-power', 'survey'],
    capacity: 84,
    speed: 1.8,
    reliability: 0.92,
    costPerMinute: 58,
    status: 'ready',
  },
  {
    id: 'r-grid-mobile',
    name: 'Mobile Substation 4',
    kind: 'power',
    homeSectorId: 'south-reservoir',
    position: { x: 49, y: 82 },
    capabilities: ['restore-power', 'water-relief'],
    capacity: 72,
    speed: 1.35,
    reliability: 0.87,
    costPerMinute: 64,
    status: 'ready',
  },
  {
    id: 'r-med-aegis',
    name: 'Aegis Triage Unit',
    kind: 'medical',
    homeSectorId: 'central-hospital',
    position: { x: 46, y: 24 },
    capabilities: ['triage', 'evacuate'],
    capacity: 78,
    speed: 1.55,
    reliability: 0.94,
    costPerMinute: 51,
    status: 'ready',
  },
  {
    id: 'r-med-campus',
    name: 'Campus Med Relay',
    kind: 'medical',
    homeSectorId: 'university-quarter',
    position: { x: 20, y: 76 },
    capabilities: ['triage', 'shelter'],
    capacity: 56,
    speed: 1.48,
    reliability: 0.88,
    costPerMinute: 39,
    status: 'ready',
  },
  {
    id: 'r-drone-vigil',
    name: 'Vigil Drone Mesh',
    kind: 'drone',
    homeSectorId: 'data-corridor',
    position: { x: 30, y: 46 },
    capabilities: ['survey', 'reroute', 'restore-network'],
    capacity: 63,
    speed: 3.1,
    reliability: 0.91,
    costPerMinute: 34,
    status: 'ready',
  },
  {
    id: 'r-drone-harbor',
    name: 'Harbor Drone Wing',
    kind: 'drone',
    homeSectorId: 'river-harbor',
    position: { x: 76, y: 29 },
    capabilities: ['survey', 'water-relief', 'supply'],
    capacity: 60,
    speed: 3.25,
    reliability: 0.9,
    costPerMinute: 36,
    status: 'ready',
  },
  {
    id: 'r-cyber-zero',
    name: 'Zero Trust Cell',
    kind: 'cyber',
    homeSectorId: 'data-corridor',
    position: { x: 32, y: 49 },
    capabilities: ['restore-network', 'reroute'],
    capacity: 69,
    speed: 2.2,
    reliability: 0.93,
    costPerMinute: 62,
    status: 'ready',
  },
  {
    id: 'r-fire-ember',
    name: 'Emberbreak Crew',
    kind: 'field',
    homeSectorId: 'airport-node',
    position: { x: 82, y: 84 },
    capabilities: ['contain-fire', 'evacuate', 'survey'],
    capacity: 74,
    speed: 1.42,
    reliability: 0.86,
    costPerMinute: 67,
    status: 'ready',
  },
  {
    id: 'r-shelter-dawn',
    name: 'Dawn Shelter Kit',
    kind: 'shelter',
    homeSectorId: 'old-city',
    position: { x: 53, y: 54 },
    capabilities: ['shelter', 'water-relief', 'supply'],
    capacity: 82,
    speed: 1.2,
    reliability: 0.89,
    costPerMinute: 45,
    status: 'ready',
  },
  {
    id: 'r-logistics-orbit',
    name: 'Orbit Convoy',
    kind: 'logistics',
    homeSectorId: 'east-artery',
    position: { x: 84, y: 58 },
    capabilities: ['supply', 'reroute', 'evacuate'],
    capacity: 91,
    speed: 1.62,
    reliability: 0.88,
    costPerMinute: 55,
    status: 'ready',
  },
]

const incidentSets: Record<string, Incident[]> = {
  monsoon: [
    {
      id: 'i-flood-harbor',
      title: 'Harbor flood gates at limit',
      kind: 'flood',
      sectorId: 'river-harbor',
      severity: 8.8,
      urgency: 9.2,
      stability: 0.35,
      demand: 92,
      startedMinutesAgo: 34,
      requiredCapabilities: ['water-relief', 'evacuate', 'survey'],
      description: 'Rising river pressure is disrupting cargo, road access, and nearby low-income housing.',
    },
    {
      id: 'i-grid-north',
      title: 'Transformer cascade risk',
      kind: 'grid',
      sectorId: 'north-grid',
      severity: 8.1,
      urgency: 8.6,
      stability: 0.42,
      demand: 86,
      startedMinutesAgo: 18,
      requiredCapabilities: ['restore-power', 'survey'],
      description: 'Load balancing is failing after two feeders tripped in the northern exchange.',
    },
    {
      id: 'i-hospital-surge',
      title: 'ER triage overflow',
      kind: 'medical',
      sectorId: 'central-hospital',
      severity: 7.7,
      urgency: 8.8,
      stability: 0.52,
      demand: 78,
      startedMinutesAgo: 46,
      requiredCapabilities: ['triage', 'evacuate'],
      description: 'Ambulance arrivals exceed staffed intake capacity and diversion options are narrowing.',
    },
    {
      id: 'i-old-city-water',
      title: 'Old City water contamination',
      kind: 'flood',
      sectorId: 'old-city',
      severity: 7.4,
      urgency: 8,
      stability: 0.39,
      demand: 84,
      startedMinutesAgo: 61,
      requiredCapabilities: ['water-relief', 'shelter', 'supply'],
      description: 'Pressure loss and backflow reports are creating localized panic in dense housing blocks.',
    },
  ],
  cyber: [
    {
      id: 'i-cyber-data',
      title: 'Transit control ransomware',
      kind: 'cyber',
      sectorId: 'data-corridor',
      severity: 8.9,
      urgency: 9.4,
      stability: 0.31,
      demand: 88,
      startedMinutesAgo: 22,
      requiredCapabilities: ['restore-network', 'reroute', 'survey'],
      description: 'Core routing systems are isolated after a coordinated credential compromise.',
    },
    {
      id: 'i-artery-jam',
      title: 'East artery signal failure',
      kind: 'logistics',
      sectorId: 'east-artery',
      severity: 7.6,
      urgency: 8.4,
      stability: 0.46,
      demand: 81,
      startedMinutesAgo: 29,
      requiredCapabilities: ['reroute', 'survey'],
      description: 'Manual traffic control cannot keep pace with evacuation and supply movement.',
    },
    {
      id: 'i-hospital-network',
      title: 'Hospital systems degraded',
      kind: 'medical',
      sectorId: 'central-hospital',
      severity: 8.2,
      urgency: 8.1,
      stability: 0.5,
      demand: 74,
      startedMinutesAgo: 37,
      requiredCapabilities: ['restore-network', 'triage'],
      description: 'Patient matching and imaging queues are delayed by intermittent network outages.',
    },
    {
      id: 'i-airport-supply',
      title: 'Airbridge manifest mismatch',
      kind: 'logistics',
      sectorId: 'airport-node',
      severity: 6.9,
      urgency: 7.5,
      stability: 0.57,
      demand: 68,
      startedMinutesAgo: 42,
      requiredCapabilities: ['supply', 'reroute'],
      description: 'Relief pallets are arriving faster than routing teams can validate destinations.',
    },
  ],
  heatfire: [
    {
      id: 'i-fire-airport',
      title: 'Fuel farm heat ignition',
      kind: 'fire',
      sectorId: 'airport-node',
      severity: 9.1,
      urgency: 9.6,
      stability: 0.26,
      demand: 96,
      startedMinutesAgo: 13,
      requiredCapabilities: ['contain-fire', 'evacuate', 'survey'],
      description: 'Thermal cameras show ignition risk near fuel handling and relief staging lanes.',
    },
    {
      id: 'i-power-heat',
      title: 'Reservoir pump outage',
      kind: 'grid',
      sectorId: 'south-reservoir',
      severity: 8,
      urgency: 8.2,
      stability: 0.44,
      demand: 79,
      startedMinutesAgo: 27,
      requiredCapabilities: ['restore-power', 'water-relief'],
      description: 'Heat stress pushed pump controls offline, reducing cooling and drinking water pressure.',
    },
    {
      id: 'i-campus-shelter',
      title: 'Campus shelter saturation',
      kind: 'medical',
      sectorId: 'university-quarter',
      severity: 7.1,
      urgency: 7.8,
      stability: 0.55,
      demand: 73,
      startedMinutesAgo: 58,
      requiredCapabilities: ['triage', 'shelter', 'supply'],
      description: 'Cooling centers are over capacity after neighborhood outages and heat exhaustion reports.',
    },
    {
      id: 'i-old-city-evac',
      title: 'Old City evacuation friction',
      kind: 'logistics',
      sectorId: 'old-city',
      severity: 7.8,
      urgency: 8.5,
      stability: 0.37,
      demand: 87,
      startedMinutesAgo: 31,
      requiredCapabilities: ['evacuate', 'reroute', 'shelter'],
      description: 'Narrow streets and conflicting orders are slowing evacuation from heat-risk buildings.',
    },
  ],
}

function cloneSectors(incidentIds: string[]) {
  const stressedSectors = new Set(incidentIds)
  return sectors.map((sector) => {
    if (!stressedSectors.has(sector.id)) return { ...sector, telemetry: { ...sector.telemetry } }
    return {
      ...sector,
      telemetry: {
        ...sector.telemetry,
        power: Math.max(42, sector.telemetry.power - 14),
        medical: Math.max(38, sector.telemetry.medical - 11),
        mobility: Math.max(34, sector.telemetry.mobility - 13),
        network: Math.max(37, sector.telemetry.network - 12),
        water: Math.max(35, sector.telemetry.water - 12),
        trust: Math.max(34, sector.telemetry.trust - 10),
      },
    }
  })
}

function cloneResources() {
  return resources.map((resource) => ({ ...resource, position: { ...resource.position } }))
}

function buildScenario(
  id: keyof typeof incidentSets,
  name: string,
  tagline: string,
  pressure: string,
  briefing: string,
  objectives: string[],
  seed: number,
): Scenario {
  const incidentSet = incidentSets[id]
  if (!incidentSet) throw new Error(`Missing incident set ${id}.`)
  const incidents = incidentSet.map((incident) => ({ ...incident }))
  return {
    id,
    name,
    tagline,
    pressure,
    briefing,
    objectives,
    seed,
    sectors: cloneSectors(incidents.map((incident) => incident.sectorId)),
    resources: cloneResources(),
    incidents,
  }
}

export const scenarios: Scenario[] = [
  buildScenario(
    'monsoon',
    'Monsoon Surge',
    'Flood, grid, and hospital stress converge in the same 90-minute window.',
    'Hydrology + power instability',
    'A city-scale monsoon event is pushing river gates, grid redundancy, hospital intake, and water safety at once.',
    [
      'Keep hospital intake below diversion threshold',
      'Protect dense housing before trust collapses',
      'Restore critical power without starving flood response',
    ],
    2401,
  ),
  buildScenario(
    'cyber',
    'Cyber Blackout',
    'A coordinated attack breaks transit routing while hospitals and airbridge logistics degrade.',
    'Network integrity + mobility',
    'The city still has physical resources, but software coordination is failing across transit, hospital systems, and relief staging.',
    [
      'Regain routing authority in the data corridor',
      'Keep ambulance travel time below critical delay',
      'Prevent supply misallocation at the airbridge',
    ],
    9307,
  ),
  buildScenario(
    'heatfire',
    'Heatfire Cascade',
    'Extreme heat, ignition risk, water pressure, and evacuation friction combine into a fast cascade.',
    'Thermal risk + water pressure',
    'A heat dome has turned ordinary outages into a compounding fire, medical, and water reliability event.',
    [
      'Contain ignition risk near the airport relief node',
      'Restore reservoir pump reliability',
      'Open cooling and evacuation capacity for dense blocks',
    ],
    11813,
  ),
]

export const defaultPolicy = {
  responseBias: 0.68,
  equityBias: 0.74,
  budgetGuardrail: 0.42,
  automationLevel: 0.71,
}
